wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.3
hidden_dims:
  value: '32'
lr:
  value: 0.004692102362164249
n_epochs:
  value: 1000
optimizer:
  value: adamw
patience:
  value: 50
weight_decay:
  value: 0.0030435832046704745
