wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.1
hidden_dims:
  value: '128_64'
lr:
  value: 0.000849620552553241
n_epochs:
  value: 1000
optimizer:
  value: adamw
patience:
  value: 100
weight_decay:
  value: 0.0007466139490206894
