wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0
hidden_dims:
  value: '32'
lr:
  value: 0.0007369863048148755
n_epochs:
  value: 1000
optimizer:
  value: adamw
patience:
  value: 50
weight_decay:
  value: 0.0008504855978664106
