wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.1
hidden_dims:
  value: '256_128'
lr:
  value: 0.00030734719601565566
n_epochs:
  value: 1000
optimizer:
  value: adamw
patience:
  value: 20
weight_decay:
  value: 0.0008794340035367484
