wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0
hidden_dims:
  value: '256_128'
lr:
  value: 0.00030952538267216636
n_epochs:
  value: 1000
optimizer:
  value: adamw
patience:
  value: 50
weight_decay:
  value: 3.1761568489394166e-05
