wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.2
hidden_dims:
  value: '256_128'
lr:
  value: 0.00032058101622446807
n_epochs:
  value: 1000
optimizer:
  value: adamw
patience:
  value: 20
weight_decay:
  value: 1.5932848596123603e-05
