wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5
hidden_dims:
  value: '64_32'
lr:
  value: 0.00041636818221094015
n_epochs:
  value: 1000
optimizer:
  value: adamw
patience:
  value: 100
weight_decay:
  value: 0.024963069997245367
