wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0
hidden_dims:
  value: '256_128'
lr:
  value: 0.0003253586701020435
n_epochs:
  value: 1000
optimizer:
  value: adamw
patience:
  value: 20
weight_decay:
  value: 0.00026188236330707275
